env:
  TERM: xterm-256color

window:
  decorations: buttonless
  padding:
    x: 3
    y: 5

selection:
  save_to_clipboard: true

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Retina
  size: 12.0

colors:
  # Default colors
  primary:
    background: '0x24283b'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x1d202f'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }

key_bindings:
  - { key: Space, mods: Control, chars: "\x00" }
  - { key: Period, mods: Control, chars: "\x1b[46;5u" }
