#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
$HOME/.config/yabai/spaces.sh

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

yabai -m config external_bar               all:30:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                window_border_width        2            \
                window_border_radius       11           \
                window_border_hidpi         on      \
                window_animation_duration  0.0         \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                6           \
                bottom_padding             6           \
                left_padding               6           \
                right_padding              6           \
                window_gap                 6

yabai -m config layout bsp


yabai -m space 1 --label space.1
yabai -m space 2 --label space.2
yabai -m space 3 --label space.3
yabai -m space 4 --label space.4
yabai -m space 5 --label space.5
yabai -m space 6 --label space.6
yabai -m space 7 --label space.7




yabai -m signal --add event=display_added action="$HOME/.config/yabai/spaces.sh"
yabai -m signal --add event=display_removed action="$HOME/.config/yabai/spaces.sh"

# focus on space change
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# rules
yabai -m rule --add title='mylauncher' manage=off sticky=on layer=above border=off
yabai -m rule --add app="^VLC$" border=off
yabai -m rule --add app="^System Preferences$" layer=above manage=off
yabai -m rule --add app="^Obsidian$" space=space.3

# yabai -m rule --add app!="^(Google Chrome|Obsidian|Finder|Alacritty)$" manage=off


printf "yabai: configuration loaded...\\n"
