#!/usr/bin/env bash
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
$HOME/.config/yabai/spaces.sh


# events
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/spaces.sh"

# focus on space change
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"


yabai -m config external_bar               off:0:0     \
                window_border              on           \
                mouse_follows_focus         on           \
                focus_follows_mouse         autoraise    \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              off        \
                window_opacity             off           \
                active_window_opacity      1.0          \
                normal_window_opacity      1.0         \
                window_border_width        4            \
                window_border_radius       12           \
                window_border_hidpi        on      \
                window_animation_duration  0.0         \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                split_type                  auto         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                8           \
                bottom_padding             8           \
                left_padding               8           \
                right_padding              8           \
                window_gap                 8 

yabai -m config layout bsp



# rules
yabai -m rule --add title='mylauncher' manage=off sticky=on layer=above border=off
yabai -m rule --add app="^VLC$" border=off
yabai -m rule --add app="^System Preferences$" layer=above manage=off
yabai -m rule --add app="^Obsidian$" space=5

# yabai -m rule --add app!="^(Google Chrome|Obsidian|Finder|Alacritty)$" manage=off


printf "yabai: configuration loaded...\\n"
